# Menggunakan versi Docker Compose 3.7
version: '3.7'

services:
  # Service untuk item-app
  item-app:
    # Menggunakan image dari GitHub Container Registry atau Docker Hub
    image: medomeckz/item-app:v1
    
    # Memetakan port 80 pada container ke port 80 di host, sehingga bisa diakses melalui port 80 di localhost
    ports:
      - 80:8080
    
    # Service item-app akan dijalankan setelah item-db berhasil dijalankan
    depends_on:
      - item-db
    
    # Menambahkan restart policy agar container selalu restart jika terhenti atau gagal
    restart: always
    
    # Konfigurasi logging untuk membatasi ukuran dan jumlah file log
    logging:
      driver: json-file
      options:
        max-size: 5m    # Ukuran maksimal file log adalah 5MB
        max-file: 5     # Maksimal terdapat 5 file log
    
  # Service untuk database (MongoDB)
  item-db:
    # Menggunakan image MongoDB versi 3 dari Docker Hub
    image: mongo:3
    
    # Menggunakan volume app-db dan mount ke /data/db di container MongoDB
    volumes:
      - app-db:/data/db
    
    # Menambahkan restart policy agar service selalu restart jika terhenti
    restart: always

# Definisi volume yang digunakan untuk menyimpan data database MongoDB
volumes:
  app-db:
